<-PYT:locale.getdefaultlocale()
->RET:raise exceptions.ValueError('unknown locale: xx_XX')
